### ISSUE TITLE
Setup Streamlit sharing

### ISSUE THREAD

**Issue by Hamdymi** [CMU-IDS-2021/fp--05839-pozioma-ahamdala-akintayj-mfinch#4]
Dear TAs, please add our repo to Streamlit sharing and then respond to this issue with the URL to the deployed application.

**Comment by kai-qu** [comment]
https://share.streamlit.io/cmu-ids-2021/fp--05839-pozioma-ahamdala-akintayj-mfinch/main/scs/python/app.py
